stages: 
 - build 

ubuntu1604:
  stage: build
  image: docker-registry.csc.mpi-magdeburg.mpg.de:5000/ci-images/minimal/ubuntu:xenial
  script:
    - apt update && apt install --yes libopenblas-dev libblas-dev liblapack-dev
    - mkdir -p build 
    - cd build
    - cmake ../ -DDEBUG=ON 
    - make 
    - make test

ubuntu1804:
  stage: build
  image: docker-registry.csc.mpi-magdeburg.mpg.de:5000/ci-images/minimal/ubuntu:bionic
  script:
    - apt update && apt install --yes libopenblas-dev libblas-dev liblapack-dev
    - mkdir -p build 
    - cd build
    - cmake ../ -DDEBUG=ON 
    - make 
    - make test

ubuntu2004:
  stage: build
  image: docker-registry.csc.mpi-magdeburg.mpg.de:5000/ci-images/minimal/ubuntu:focal
  script:
    - apt update && apt install --yes libopenblas-dev libblas-dev liblapack-dev
    - mkdir -p build
    - cd build
    - cmake ../ -DDEBUG=ON 
    - make 
    - make test
    
centos7:
  stage: build
  image: docker-registry.csc.mpi-magdeburg.mpg.de:5000/ci-images/minimal/centos:7-base
  script:
    - yum install -y cmake3 blas-devel lapack-devel 
    - mkdir -p build
    - cd build
    - cmake3 ../ -DDEBUG=ON 
    - make 
    - make test

centos8:
  stage: build
  image: docker-registry.csc.mpi-magdeburg.mpg.de:5000/ci-images/minimal/centos:8-base
  script:
    - yum install -y blas-devel lapack-devel 
    - mkdir -p build
    - cd build
    - cmake ../ -DDEBUG=ON 
    - make 
    - make test

