stages: 
 - build 

ubuntu1604:
  stage: build
  image: docker-registry.csc.mpi-magdeburg.mpg.de:5000/ci-images/minimal/ubuntu:xenial
  script:
    - apt update && apt install --yes libopenblas-dev libblas-dev liblapack-dev
    - mkdir -p build 
    - cd build
    - cmake ../ -DDEBUG=ON 
    - make 
    - make test

ubuntu1804:
  stage: build
  image: docker-registry.csc.mpi-magdeburg.mpg.de:5000/ci-images/minimal/ubuntu:xenial
  script:
    - apt update && apt install --yes libopenblas-dev libblas-dev liblapack-dev
    - mkdir -p build 
    - cd build
    - cmake ../ -DDEBUG=ON 
    - make 
    - make test

ubuntu2004:
  stage: build
  image: docker-registry.csc.mpi-magdeburg.mpg.de:5000/ci-images/minimal/ubuntu:xenial
  script:
    - apt update && apt install --yes libopenblas-dev libblas-dev liblapack-dev
    - mkdir -p build
    - cd build
    - cmake ../ -DDEBUG=ON 
    - make 
    - make test
